# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [2]:
# Import torch

import torch
# Create random tensor
tensor =torch.rand(7,7)
tensor

tensor([[0.5102, 0.6277, 0.6038, 0.4059, 0.5476, 0.8222, 0.0528],
        [0.0222, 0.7933, 0.5290, 0.9056, 0.2626, 0.8313, 0.3934],
        [0.8122, 0.7498, 0.7369, 0.7493, 0.0651, 0.8633, 0.9156],
        [0.0331, 0.6599, 0.4630, 0.1457, 0.6971, 0.2482, 0.3061],
        [0.0501, 0.4683, 0.9304, 0.4829, 0.8870, 0.2715, 0.7741],
        [0.7293, 0.9513, 0.8883, 0.6332, 0.9566, 0.3752, 0.6241],
        [0.2272, 0.8636, 0.3615, 0.9417, 0.3943, 0.0721, 0.3080]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [5]:
# Create another random tensor
another_tensor = torch.rand(1,7)
# Perform matrix multiplication
torch.matmul(tensor,another_tensor.T)

tensor([[1.1379],
        [0.9705],
        [1.8726],
        [0.7946],
        [1.3223],
        [1.8624],
        [0.8920]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [11]:
# Set manual seed
RANDOM_SEED = 0

# Create two random tensors
torch.manual_seed(RANDOM_SEED)
tensor_A = torch.rand(7,7)
tensor_B = torch.rand(1,7)

# Matrix multiply tensors
torch.matmul(tensor_A,tensor_B.T)

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [13]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [18]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
device= "cuda" if torch.cuda.is_available() else  "cpu"
device
# Create two random tensors on GPU
tensor_A = torch.rand(2,3).to(device)
tensor_B = torch.rand(2,3).to(device)
tensor_A, tensor_B

(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [36]:
# Perform matmul on tensor_A and tensor_B
resultant_tensor =torch.matmul(tensor_A,tensor_B.T)

### 8. Find the maximum and minimum values of the output of 7.

In [37]:
# # Find max
print(torch.max(resultant_tensor))
# # Find min
print(torch.min(resultant_tensor))


tensor(0.5617, device='cuda:0')
tensor(0.3647, device='cuda:0')


### 9. Find the maximum and minimum index values of the output of 7.

In [38]:
# Find arg max
print(torch.argmax(resultant_tensor))

# Find arg min
print(torch.argmin(resultant_tensor))

tensor(3, device='cuda:0')
tensor(0, device='cuda:0')



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [41]:
# Set seed

torch.manual_seed(7)
# Create random tensor
tensor = torch.rand(1,1,1,10)

# Remove single dimensions
squeezed_tensor = torch.squeeze(tensor)

# Print out tensors and their shapes
tensor, tensor.shape, squeezed_tensor, squeezed_tensor.shape

(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
            0.3653, 0.8513]]]]),
 torch.Size([1, 1, 1, 10]),
 tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]),
 torch.Size([10]))